# Generated by Django 4.1.5 on 2023-01-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_loaction_profile_location_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, default='blank-pfp.png', null=True, upload_to='uploads/pfp/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='<django.db.models.query_utils.DeferredAttribute object at 0x00000175A03F7EB0>', max_length=255),
        ),
    ]
