# Generated by Django 4.1.5 on 2023-01-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_post_user_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(default='dummy', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000001AB87E57EB0>', max_length=255),
        ),
    ]
